/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        page: 'var(--bg-page)',
        panel: 'var(--bg-panel)',
        sidebar: 'var(--bg-sidebar)',
        hover: 'var(--bg-hover)',
        active: 'var(--bg-active)',
        input: 'var(--bg-input)',
        code: 'var(--bg-code)',
        't-primary': 'var(--text-primary)',
        't-secondary': 'var(--text-secondary)',
        't-tertiary': 'var(--text-tertiary)',
        't-inverse': 'var(--text-inverse)',
        'b-color': 'var(--border-color)',
        'b-divider': 'var(--border-divider)',
        'a-primary': 'var(--accent-primary)',
        'a-link': 'var(--accent-link)',
        'm-user-bg': 'var(--msg-user-bg)',
        'm-user-border': 'var(--msg-user-border)',
        'm-agent-bg': 'var(--msg-agent-bg)',
        'm-agent-border': 'var(--msg-agent-border)',
        'm-tool-bg': 'var(--msg-tool-bg)',
        'm-tool-border': 'var(--msg-tool-border)',
        'm-approval-bg': 'var(--msg-approval-bg)',
        'm-approval-border': 'var(--msg-approval-border)',
        's-running': 'var(--status-running)',
        's-stopped': 'var(--status-stopped)',
        's-error': 'var(--status-error)',
        's-pending': 'var(--status-pending)',
        's-waiting': 'var(--status-waiting)',
      },
      fontFamily: {
        sans: ["'DM Sans'", 'system-ui', "'PingFang SC'", "'Microsoft YaHei'", 'sans-serif'],
        mono: ["'JetBrains Mono'", 'monospace'],
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
      },
    },
  },
  plugins: [],
}
